version: '3.8'

services:
  notes-service:
    build: ./backend/notes_service
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres-notes
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/notes_service/app:/code/app

  users-service:
    build: ./backend/users_service
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres-users
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/users_service/app:/code/app

  postgres-notes:
    image: postgres:15-alpine
    container_name: postgres-notes
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - notes_db_data:/var/lib/postgresql/data
  
  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - "5433:5432"  # Different host port to avoid conflict
    volumes:
      - users_db_data:/var/lib/postgresql/data

# Persistent Volume
volumes:
  notes_db_data:
  users_db_data: