version: '3.8'

services:
  # notes-service:
  #   build: ./backend/notes_service
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=notes
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     - postgres
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - notes_db_data:/var/lib/postgresql/data

# Persistent Volume
volumes:
  notes_db_data: