apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging
  labels:
    app: frontend
spec:
  replicas: 3 # high availability, load distribution, and rolling update capabilities
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: sit722aliceacr.azurecr.io/_IMAGE_NAME_WITH_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Nginx runs on port 80 inside the container
          restartPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend # Service name matches
  namespace: staging
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service listens on inside the cluster
      targetPort: 80 # The port on the Pod (containerPort where Nginx runs)
  type: LoadBalancer # Exposes the service on a port on each Node's IP
