apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service-deployment
  namespace: staging
  labels:
    app: notes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:ners:
      - name: notes-service-container
        image: sit722aliceacr.azurecr.io/_IMAGE_NAME_WITH_TAG_
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: POSTGRES_DB
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: ENVIRONMENT
        - name: USERS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: USERS_SERVICE_URL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: notes-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notes-secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notes-service
  namespace: staging
  labels:
    app: notes-service
spec:
  selector:
    app: notes-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
