apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment # Deployment name matches
  namespace: staging
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service-container
        image: sit722aliceacr.azurecr.io/users-service:staging-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: POSTGRES_DB
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: ENVIRONMENT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: notes-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notes-secrets
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: staging
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
