name: CD - Staging Tests on PR

on:
  # Manual trigger
  workflow_dispatch:

  # Run the test when the new PR to develop is created
  # pull_request:
  #   branches:
  #     - develop
  #   paths:
  #     - 'backend/**'
  #     - 'frontend/**'
  #     - 'k8s/staging/**'
  #     - 'infrastructure/staging/**'
  #     - '.github/workflows/*staging*.yml'
  
  workflow_call:
    inputs:
      frontend_url:
        required: true
        type: string
      product_service_url:
        required: true
        type: string

env:
  PYTHON_VERSION: "3.10"

jobs:
  # Test Individual Services (Already triggered on feature_test workflows)

  # Acceptance Tests (End-to-End)
  acceptance-tests:
    name: Acceptance Tests - End-to-end user flow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        
      - name: Start services with Docker Compose
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          timeout 60 bash -c 'until curl -s http://localhost:5000/health > /dev/null; do sleep 2; done'
          timeout 60 bash -c 'until curl -s http://localhost:5001/health > /dev/null; do sleep 2; done'
          timeout 60 bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 2; done'
          echo "Services are ready!"
      
      - name: Install Playwright
        run: |
          cd ./playwright-python
          echo "Installing Playwright..."
          pip install pytest-playwright
          playwright install
          pip install -r requirements.txt

      - name: Run acceptance tests
        run: |
          echo "Runing acceptance tests with Playwright..."
          cd ./playwright-python
          pytest ./playwright-python/tests/test_acceptance.py -v
          
      - name: Stop services
        if: always()
        run: |
          docker compose down -v