name: Feature Branch CI - Note Service

# Workflow runs on any changes on Note Services, commited on feature or fix branches
on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
    paths: 
      - "backend/notes_service/**"

jobs:
  quality-checks:
    name: Quality Check for Notes Service
    uses: ./.github/workflows/_reusable_quality_check_workflow.yml
    secrets: inherit
    with:
      working-directory: "./backend/notes_service"
      linting-threshold: 6.0

  test:
    name: Run Tests for Notes Service
    uses: ./.github/workflows/_reusable_test_workflow.yml
    secrets: inherit
    with:
      working-directory: "./backend/notes_service"
      coverage-threshold: 80